-- =========================================================
-- AUTO GENERATED MENU SYNC SQL
-- generated by tools/gen_menu_sync.js
-- =========================================================

-- parents
INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES ('m_projects_root', 'projects', 'Projects', '/projects', NULL, 109, 'fa-solid fa-diagram-project', strftime('%s','now'), 'system');
UPDATE menus SET code='projects', label='Projects', path='/projects', parent_id=NULL, sort_order=109, icon='fa-solid fa-diagram-project', group_key='system' WHERE id='m_projects_root';

INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES ('m_cert_root', 'certificates', 'Certificates', '/certificates', NULL, 110, 'fa-solid fa-certificate', strftime('%s','now'), 'system');
UPDATE menus SET code='certificates', label='Certificates', path='/certificates', parent_id=NULL, sort_order=110, icon='fa-solid fa-certificate', group_key='system' WHERE id='m_cert_root';

INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES ('m_proj_archive_root', 'projects_archive', 'Project Archive', '/projects/archive', 'm_projects_root', 113, 'fa-solid fa-box-archive', strftime('%s','now'), 'system');
UPDATE menus SET code='projects_archive', label='Project Archive', path='/projects/archive', parent_id='m_projects_root', sort_order=113, icon='fa-solid fa-box-archive', group_key='system' WHERE id='m_proj_archive_root';

-- children
INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES ('m_cert_templates', 'certificate_templates', 'Certificate Templates', '/certificates/templates', 'm_cert_root', 111, 'fa-solid fa-file-signature', strftime('%s','now'), 'system');
UPDATE menus SET code='certificate_templates', label='Certificate Templates', path='/certificates/templates', parent_id='m_cert_root', sort_order=111, icon='fa-solid fa-file-signature', group_key='system' WHERE id='m_cert_templates';

INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES ('m_cert_issue', 'certificate_issue', 'Issue Certificates', '/certificates/issue', 'm_cert_root', 112, 'fa-solid fa-award', strftime('%s','now'), 'system');
UPDATE menus SET code='certificate_issue', label='Issue Certificates', path='/certificates/issue', parent_id='m_cert_root', sort_order=112, icon='fa-solid fa-award', group_key='system' WHERE id='m_cert_issue';

INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES ('m_proj_finish_bulk', 'projects_finish_bulk', 'Finish Project Bulk', '/projects/finish-bulk', 'm_proj_archive_root', 114, 'fa-solid fa-flag-checkered', strftime('%s','now'), 'system');
UPDATE menus SET code='projects_finish_bulk', label='Finish Project Bulk', path='/projects/finish-bulk', parent_id='m_proj_archive_root', sort_order=114, icon='fa-solid fa-flag-checkered', group_key='system' WHERE id='m_proj_finish_bulk';

INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES ('m_proj_archive_view', 'projects_archive_view', 'Archived Projects', '/projects/archive-view', 'm_proj_archive_root', 115, 'fa-solid fa-box-archive', strftime('%s','now'), 'system');
UPDATE menus SET code='projects_archive_view', label='Archived Projects', path='/projects/archive-view', parent_id='m_proj_archive_root', sort_order=115, icon='fa-solid fa-box-archive', group_key='system' WHERE id='m_proj_archive_view';

-- role mappings
INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, 'm_projects_root', strftime('%s','now')
FROM roles r
WHERE r.name IN ('super_admin', 'admin', 'staff');

INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, 'm_cert_root', strftime('%s','now')
FROM roles r
WHERE r.name IN ('super_admin', 'admin', 'staff');

INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, 'm_proj_archive_root', strftime('%s','now')
FROM roles r
WHERE r.name IN ('super_admin', 'admin', 'staff');

INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, 'm_cert_templates', strftime('%s','now')
FROM roles r
WHERE r.name IN ('super_admin');

INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, 'm_cert_issue', strftime('%s','now')
FROM roles r
WHERE r.name IN ('super_admin', 'admin', 'staff');

INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, 'm_proj_finish_bulk', strftime('%s','now')
FROM roles r
WHERE r.name IN ('super_admin', 'admin', 'staff');

INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, 'm_proj_archive_view', strftime('%s','now')
FROM roles r
WHERE r.name IN ('super_admin', 'admin', 'staff');

-- verification
SELECT id, code, label, path, parent_id, sort_order FROM menus
WHERE id IN ('m_projects_root', 'm_cert_root', 'm_proj_archive_root', 'm_cert_templates', 'm_cert_issue', 'm_proj_finish_bulk', 'm_proj_archive_view')
ORDER BY sort_order ASC, id ASC;

SELECT r.name AS role_name, m.id AS menu_id, m.label, m.path
FROM role_menus rm
JOIN roles r ON r.id = rm.role_id
JOIN menus m ON m.id = rm.menu_id
WHERE m.id IN ('m_projects_root', 'm_cert_root', 'm_proj_archive_root', 'm_cert_templates', 'm_cert_issue', 'm_proj_finish_bulk', 'm_proj_archive_view')
ORDER BY r.name ASC, m.sort_order ASC, m.id ASC;