const fs = require("fs");
const path = require("path");

const cfgPath = path.join(process.cwd(), "tools", "menu_sync_config.json");
const outPath = path.join(process.cwd(), "menu_sync_generated.sql");

function sqlStr(v){
  if(v === null || v === undefined) return "NULL";
  return "'" + String(v).replace(/'/g, "''") + "'";
}

function assertMenu(m){
  const required = ["id", "code", "label", "path", "sort_order", "icon"];
  for(const k of required){
    if(m[k] === undefined || m[k] === null || String(m[k]).trim() === ""){
      throw new Error(`menu missing field: ${k} for id=${m.id || "unknown"}`);
    }
  }
  if(!Array.isArray(m.roles)) throw new Error(`menu roles must be array for id=${m.id}`);
}

function uniqueCheck(items, field){
  const seen = new Map();
  for(const x of items){
    const v = String(x[field] ?? "");
    if(seen.has(v)){
      throw new Error(`duplicate ${field}: ${v} on ${seen.get(v)} and ${x.id}`);
    }
    seen.set(v, x.id);
  }
}

function genMenuSql(m){
  const parentId = m.parent_id == null ? "NULL" : sqlStr(m.parent_id);
  const groupKey = m.group_key == null ? "NULL" : sqlStr(m.group_key);
  return [
    `INSERT OR IGNORE INTO menus (id, code, label, path, parent_id, sort_order, icon, created_at, group_key) VALUES (${sqlStr(m.id)}, ${sqlStr(m.code)}, ${sqlStr(m.label)}, ${sqlStr(m.path)}, ${parentId}, ${Number(m.sort_order)}, ${sqlStr(m.icon)}, strftime('%s','now'), ${groupKey});`,
    `UPDATE menus SET code=${sqlStr(m.code)}, label=${sqlStr(m.label)}, path=${sqlStr(m.path)}, parent_id=${parentId}, sort_order=${Number(m.sort_order)}, icon=${sqlStr(m.icon)}, group_key=${groupKey} WHERE id=${sqlStr(m.id)};`
  ].join("\n");
}

function genRoleSql(m){
  const roles = m.roles.map(sqlStr).join(", ");
  return `INSERT OR IGNORE INTO role_menus (role_id, menu_id, created_at)
SELECT r.id, ${sqlStr(m.id)}, strftime('%s','now')
FROM roles r
WHERE r.name IN (${roles});`;
}

function main(){
  const raw = fs.readFileSync(cfgPath, "utf8");
  const cfg = JSON.parse(raw);

  const parents = Array.isArray(cfg.parents) ? cfg.parents : [];
  const children = Array.isArray(cfg.children) ? cfg.children : [];
  const all = [...parents, ...children];

  all.forEach(assertMenu);
  uniqueCheck(all, "id");
  uniqueCheck(all, "code");
  uniqueCheck(all, "path");

  const parentIds = new Set(parents.map(x => x.id));
  for(const c of children){
    if(c.parent_id && !parentIds.has(c.parent_id)){
      throw new Error(`child ${c.id} references missing parent_id=${c.parent_id}`);
    }
  }

  const lines = [];
  lines.push("-- =========================================================");
  lines.push("-- AUTO GENERATED MENU SYNC SQL");
  lines.push("-- generated by tools/gen_menu_sync.js");
  lines.push("-- =========================================================");
  lines.push("");

  lines.push("-- parents");
  for(const m of parents){
    lines.push(genMenuSql(m));
    lines.push("");
  }

  lines.push("-- children");
  for(const m of children){
    lines.push(genMenuSql(m));
    lines.push("");
  }

  lines.push("-- role mappings");
  for(const m of all){
    lines.push(genRoleSql(m));
    lines.push("");
  }

  lines.push("-- verification");
  lines.push("SELECT id, code, label, path, parent_id, sort_order FROM menus");
  lines.push("WHERE id IN (" + all.map(x => sqlStr(x.id)).join(", ") + ")");
  lines.push("ORDER BY sort_order ASC, id ASC;");
  lines.push("");
  lines.push("SELECT r.name AS role_name, m.id AS menu_id, m.label, m.path");
  lines.push("FROM role_menus rm");
  lines.push("JOIN roles r ON r.id = rm.role_id");
  lines.push("JOIN menus m ON m.id = rm.menu_id");
  lines.push("WHERE m.id IN (" + all.map(x => sqlStr(x.id)).join(", ") + ")");
  lines.push("ORDER BY r.name ASC, m.sort_order ASC, m.id ASC;");

  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log("[OK] wrote " + outPath);
  console.log("[INFO] total menus:", all.length);
}

main();
